# -*- coding: utf-8 -*-
"""CP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s76rwT5DQN430zd1nifZnqQ-82_tUIKF

# ***EXERCICIO 1***
"""

#funções do exercicio:
def precoCarga(codigoCarga):
    if codigoCarga <= 20:
      return  100
    elif codigoCarga <= 30:
      return 250
    else:
      return 340

def imposto(estado):
    match(estado):
        case 1:
          return 35/100
        case 2:
          return 25/100
        case 3:
            return 15/100
        case 4:
            return 5/100
        case _:
            return 0

#solicita e verifica o codigo do estado de origem
estado = int(input("Diga o código do estado: "))

#solicita o peso
peso = float(input("Peso da carga(em toneladas): "))

#solicita e verifica o codigo da carga
codigoCarga = int(input("Diga o codigo da carga: "))

#transforma toneladas em kilos
kilos = peso*1000
print(f"Peso total do caminhão em kilos: {kilos:.2f}.")
print()

#verifica o preço da carga do caminhão
preco = kilos*precoCarga(codigoCarga)
print(f"Preço total da carga: {preco:.2f}")
print()

#verifica o valor do imposto
valorImposto = imposto(estado)
print("Valor do imposto: ", valorImposto*100,"%")
print()

#Valor total da carga
valorTotal = preco + preco*valorImposto
print(f"Valor total da carga: {valorTotal:.2f}")
print()

"""# ***EXERCICIO 2***"""

#solicita os lados
ladoA = input("Lado A: ")
ladoB = input("Lado B: ")
ladoC = input("Lado C: ")

#verifica se é um triangulo
if ladoA < ladoB + ladoC:
    print("Não é um triangulo")
#realiza todas as operações solicita no exercicio
else:
    #verifica se é retangulo, obtusangulo ou acutangulo
    if ladoA*ladoA == ladoB*ladoB + ladoC*ladoC:
        print("Triangulo retangulo")
    elif ladoA*ladoA > ladoB*ladoB + ladoC*ladoC:
        print("Triangulo obtusangulo")
    else:
        print("Triangulo acutangulo")
    #verifica se é equilatero, isosceles ou escaleno
    if ladoA == ladoB == ladoC:
        print("Triangulo equilatero")
    elif ladoA == ladoB or ladoA == ladoC or ladoB == ladoC:
        print("Triangulo isosceles")
    else:
        print("Triangulo escaleno")

"""# ***EXERCICIO 3***"""

#Funções
def extra(horasExtras, salario):
    return horasExtras*salario*0.015

def desconto(faltas, salario):
    return faltas*salario*0.02

def calculaBonus(bonus, cargo):
    if bonus == "S":
      match cargo:
          case 1:
              return 1000
          case 2:
              return 500
          case 3:
              return 300
          case _:
              return 100

#realiza as solicitações
nome = input("Nome do funcionário: ")
cargo = int(input("Cargo(1-Gerente, 2-Analista, 3-Assistente, 4-Estagiario)"))

salario = float(input("Salario atual: "))
horasExtras = float(input("Horas extras trabalhadas: "))
faltas = int(input("Faltas: "))
bonus = input("Recebeu bonus? (S/N)")

#calcula e imprime
print(f"Salario bruto do funcionario {nome}: {salario}")
print("total de acrescimos: ", extra(horasExtras, salario) + calculaBonus(bonus, cargo))
print("Total de descontos: ", (desconto(faltas, salario)))
print("Salario liquido: ", (salario - desconto(faltas, salario) + extra(horasExtras, salario) + calculaBonus(bonus, cargo)))

"""# ***EXERCICIO 4***



"""

#funções
def aprovado(i, rM, vE, nP):
    if i < 18 or vE > rM*15 or vE/nP < 100 or vE/nP > 2000:
        return False
    else:
        return True

def juros(vE, nP):
    if nP <= 6:
        return 0.05
    elif nP <= 12:
        return 0.08
    else:
        return 0.10

def parcelaFinal(vE, nP):
    return vE/nP

#Solicitações
nome = input("Diga o nome do cliente: ")
idade = int(input("Diga a idade do cliente: "))
rendaMensal = float(input("Diga a renda mensal do cliente: "))
valorEmprestimo = float(input("Diga o valor do empréstimo: "))
numeroParcelas = int(input("Diga o número de parcelas (de 3 a 24): "))

#calculos
jurosFinal = valorEmprestimo*juros(valorEmprestimo, numeroParcelas)
valorParcelas = (valorEmprestimo + valorEmprestimo*juros(valorEmprestimo, numeroParcelas))/numeroParcelas
valorFinalEmprestimo = (valorEmprestimo + jurosFinal)

#verificações
if aprovado(idade, rendaMensal, valorEmprestimo, numeroParcelas):
    print("empréstimo aprovado")
    print("Valor final do empréstimo com juros: ", valorFinalEmprestimo)
    print("Valor das parcelas: ", valorParcelas)
    print("Juros total pago: ", jurosFinal)
else:
    print("Empréstimo não aprovado")